### ISSUE TITLE
Crashes Logic 2.4

### ISSUE THREAD

**Issue by Nocturnal42** [pierremolinaro/can20B-plugin-for-saleae-logic-analyzer#2]
As soon as start a capture or load a capture with this analyzer enabled, logic 2.4 crashes. I get the same result with your CAN FD analyzer as well.

**Comment by pierremolinaro** [comment]
Hello,

You run the software under MacOS, Windows, or Linux ?

I hadn't used Logic2 for a while, and indeed I'm seeing crashes with Logic 2.4.0 when I start a capture. I am on MacOS 12.6.

I suspect that the data table filling is the cause of these crashes. It uses the "FrameV2" API.

I have just published a release for both analyzers where I removed the data table generation and all references to the "FrameV2" API.

Can you tell me if you still see crashes?

Pierre

**Comment by Nocturnal42** [comment]
Running on windows. Still getting crashes with the new release unfortunately.

**Comment by pierremolinaro** [comment]
Thank you for your answer.

The bug will be difficult to solve, the Mac application does not crash anymore. I don't have a machine running on Windows at my disposal.

I did a detailed code review and may have found something. I have made version 1.1.2-beta1 for the CAN analyzer. Now the data table fills up and so does the terminal. Can you try it?

I did not modify the CANFD parser.

Pierre

**Comment by Nocturnal42** [comment]
The beta version seems to be working without crashing.

**Comment by pierremolinaro** [comment]
Fine ! I'll make a new release and update the CANFD analyzer.

Pierre
